version: '1.0.0'

random_state: 325

data:
  data_dir: 'data'
  raw_data_path: 'Python_Data_Science_and_Machine_Learning_project1_Dataset.zip'
  cleaned_data_path: 'data/data_cleaned.csv'
  test_size: 0.2

features:
  non_informatives: ['status', 'lsoa_of_casualty', 'accident_year', 'accident_reference',
                     'pedestrian_road_maintenance_worker', 'bus_or_coach_passenger',
                     'car_passenger', 'pedestrian_movement', 'pedestrian_location',
                     'age_band_of_casualty', 'accident_index']
  categorical_features: ['casualty_class',
                        'sex_of_casualty', 'casualty_severity',
                        'casualty_type', 'casualty_home_area_type', 'casualty_imd_decile']
  numerical_features: ['vehicle_reference', 'casualty_reference', 'age_of_casualty']
  nan_1: ['casualty_type', 'casualty_home_area_type', 'casualty_imd_decile', 'age_of_casualty']
  nan_1_9: ['sex_of_casualty'] # 9 -> Unknown or other
  target: 'casualty_severity_Slight'
